# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  lint_test:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - run: npm rebuild node-sass
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build:data
      - run: yarn build:examples
      - run: yarn lint
      - run: yarn test:CI


  release:
    docker:
      - image: circleci/node:8.11
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - run: npm rebuild node-sass
      - run: yarn prepublishOnly
      - run: npx semantic-release

  build_deploy:
    docker:
      - image: circleci/python:latest-node-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - run: npm rebuild node-sass
      - run: yarn build:CI
      - run: sudo pip install awscli
      - run: ./deploy-s3.sh

  release_deploy:
    docker:
      - image: circleci/python:latest-node-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - run: npm rebuild node-sass
      - run: yarn build:CI
      - run: npx semantic-release
      - run: sudo pip install awscli
      - run: ./deploy-s3.sh

  test_release_deploy:
    docker:
      - image: circleci/python:latest-node-browsers
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install
      - run: yarn upgrade @collab-ui/core
      - run: npm rebuild node-sass
      - run: yarn build:data
      - run: yarn build:examples
      - run: yarn lint
      - run: yarn test:CI
      - run: yarn build:CI
      - run: npx semantic-release
      - run: sudo pip install awscli
      - run: ./deploy-s3.sh


workflows:
  version: 2
  test:
    jobs:
      - lint_test

  daily_release:
    # Run the test jobs first, then the release only when all the test jobs are successful
    triggers:
      - schedule:
          cron: "30 5 * * 1,2,3,4,5"
          filters:
            branches:
              only:
                - master
    jobs:
      - test_release_deploy:
          context: Collab UI Bot
